APP_VERSION = "0.1.0"

DATE_FORMAT = "%d-%m-%Y"
REPORT_PREFIX = "Report "
LANG = {1: ("en", "English"), 2: ("it", "Italiano")}

CURRENCY_EUR = 1
CURRENCY_USD = 2
CURRENCY_CHOICES = {CURRENCY_EUR: "EUR", CURRENCY_USD: "USD"}

ETF_PRODUCTS = {"ETF-S", "ETF-M", "ETF-B"}
